version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    user: postgres
    ports:
      - 5433:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

volumes:
  postgres_volume:
    name: postgres_volume
    driver: local